import { NextRequest, NextResponse } from "next/server";
import { readAuthEnvironment } from "@/lib/auth-environment";
import { getDatabase } from "@/lib/database";
import { dateOnlyAtInstant, parseDateOnly } from "@/lib/date-time";
import { createMealPlanEntry, loadMealPlan, MealCommandError } from "@/lib/meal-repository";
import type { MealsApiResponse } from "@/lib/meals-api";
import { RequestContextError, resolveRequestContext } from "@/lib/server-request-context";
export const dynamic = "force-dynamic";
function json(body: MealsApiResponse | { error: string } | { id: string; label: string; mealSlot: string }, status = 200) { return NextResponse.json(body, { status, headers: { "Cache-Control": "no-store" } }); }
function bodyField(body: unknown, key: string): string { return typeof body === "object" && body !== null && key in body && typeof body[key as keyof typeof body] === "string" ? body[key as keyof typeof body] : ""; }
export async function GET(request: NextRequest) { try { const resolved = await resolveRequestContext(request); const now = new Date(); const requested = request.nextUrl.searchParams.get("date"); const date = requested === null ? dateOnlyAtInstant({ instant: now.toISOString(), timeZone: resolved.member.household.timeZone }) : requested; try { parseDateOnly(date); } catch { return json({ error: "Choose a valid meal-plan date." }, 400); } const result = await loadMealPlan(getDatabase(), { actor: { context: resolved.context, grants: [] }, date, now }); return json({ date, canManage: result.canManage, entries: result.entries.map((entry) => ({ id: entry.id, label: entry.label, mealSlot: entry.mealSlot })) }); } catch (error) { if (error instanceof RequestContextError) return json({ error: error.message }, error.reason === "unauthenticated" ? 401 : 409); if (error instanceof MealCommandError) return json({ error: "Meals is not available for this household member." }, 403); throw error; } }
export async function POST(request: NextRequest) { if (request.headers.get("origin") !== readAuthEnvironment().trustedOrigin) return json({ error: "The request origin is not allowed." }, 403); try { const resolved = await resolveRequestContext(request); const body: unknown = await request.json().catch(() => null); const entry = await createMealPlanEntry(getDatabase(), { actor: { context: resolved.context, grants: [] }, date: bodyField(body, "date"), mealSlot: bodyField(body, "mealSlot") as "breakfast" | "lunch" | "dinner" | "other", label: bodyField(body, "label"), commandId: bodyField(body, "commandId"), now: new Date() }); return json({ id: entry.id, label: entry.label, mealSlot: entry.mealSlot }, 201); } catch (error) { if (error instanceof RequestContextError) return json({ error: error.message }, error.reason === "unauthenticated" ? 401 : 409); if (error instanceof MealCommandError || error instanceof RangeError) return json({ error: "The meal could not be added. Check the date and details." }, 400); throw error; } }
