import { NextRequest, NextResponse } from "next/server";
import { readAuthEnvironment } from "@/lib/auth-environment";
import { getDatabase } from "@/lib/database";
import { createGroceryList, GroceryCommandError, loadGroceryLists } from "@/lib/grocery-repository";
import { RequestContextError, resolveRequestContext } from "@/lib/server-request-context";
export const dynamic = "force-dynamic";
function json(body: { lists: readonly { id: string; title: string; openItemCount: number }[]; canManage: boolean } | { error: string } | { id: string; title: string }, status = 200) { return NextResponse.json(body, { status, headers: { "Cache-Control": "no-store" } }); }
export async function GET(request: NextRequest) { try { const resolved = await resolveRequestContext(request); const result = await loadGroceryLists(getDatabase(), { actor: { context: resolved.context, grants: [] }, now: new Date() }); return json({ canManage: result.canManage, lists: result.lists.map((list) => ({ id: list.id, title: list.title, openItemCount: list._count.items })) }); } catch (error) { if (error instanceof RequestContextError) return json({ error: error.message }, error.reason === "unauthenticated" ? 401 : 409); if (error instanceof GroceryCommandError) return json({ error: "Groceries is not available for this household member." }, 403); throw error; } }
export async function POST(request: NextRequest) { if (request.headers.get("origin") !== readAuthEnvironment().trustedOrigin) return json({ error: "The request origin is not allowed." }, 403); try { const resolved = await resolveRequestContext(request); const body: unknown = await request.json().catch(() => null); const title = typeof body === "object" && body !== null && "title" in body && typeof body.title === "string" ? body.title : ""; const commandId = typeof body === "object" && body !== null && "commandId" in body && typeof body.commandId === "string" ? body.commandId : ""; const list = await createGroceryList(getDatabase(), { actor: { context: resolved.context, grants: [] }, title, commandId, now: new Date() }); return json({ id: list.id, title: list.title }, 201); } catch (error) { if (error instanceof RequestContextError) return json({ error: error.message }, error.reason === "unauthenticated" ? 401 : 409); if (error instanceof GroceryCommandError) return json({ error: "The grocery list could not be created." }, 403); throw error; } }
