import type { PrismaClient } from "../../generated/prisma/client";
import { createAuditEvent, createDomainEvent, newCorrelationId } from "./audit-event";
import { parseDateOnly, type DateOnly } from "./date-time";
import type { ActiveHouseholdContext } from "./identity-context";
import { loadHouseholdMiniAppConfiguration } from "./identity-repository";
import { activationEligibility } from "./mini-app-registry";
import { authorize, type CapabilityGrant } from "./permission-engine";

export class MealCommandError extends Error {}
type Actor = { context: ActiveHouseholdContext; grants: readonly CapabilityGrant[] };
type MealSlot = "breakfast" | "lunch" | "dinner" | "other";
const slots = new Set<MealSlot>(["breakfast", "lunch", "dinner", "other"]);
function boundedText(value: string, field: string) { const normalized = value.trim(); if (normalized.length === 0 || normalized.length > 200 || /[\r\n\u0000]/.test(normalized)) throw new MealCommandError(`${field} must be 1–200 characters without control characters.`); return normalized; }
function boundedCommandId(value: string) { if (value.trim().length === 0 || value.length > 200) throw new MealCommandError("commandId must be a bounded opaque identifier."); return value; }
async function authorizeMeals(database: PrismaClient, actor: Actor, permission: "meals.read" | "meals.manage", now: Date) {
  const member = await database.member.findFirst({ where: { id: actor.context.memberId, householdId: actor.context.householdId, authenticatedSubjectId: actor.context.authenticatedSubjectId, lifecycle: "active", OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] } });
  if (member === null || member.role === "guest") throw new MealCommandError("Meals is not available to this household member.");
  if (!authorize({ context: actor.context, role: member.role, grants: actor.grants, request: { householdId: member.householdId, permission, appId: "meals" }, now }).allowed) throw new MealCommandError("Meals is not available to this household member.");
  const configuration = await loadHouseholdMiniAppConfiguration(database, member.householdId); if (!activationEligibility("meals", configuration).eligible) throw new MealCommandError("Meals is not enabled for this household."); return member;
}
async function evidence(transaction: PrismaClient, householdId: string, memberId: string, entryId: string, now: Date) {
  const correlationId = newCorrelationId(); const audit = createAuditEvent({ householdId, actor: { type: "member", id: memberId }, action: "meal.plan.create", target: { type: "meal-plan-entry", id: entryId }, outcome: "succeeded", correlationId, causationId: null, occurredAt: now.toISOString(), metadata: {} }); const event = createDomainEvent({ householdId, aggregate: { type: "meal-plan-entry", id: entryId }, type: "meal.plan.created.v1", correlationId, causationId: audit.id, occurredAt: now.toISOString(), references: {} });
  await transaction.auditEvent.create({ data: { id: audit.id, householdId: audit.householdId, actorType: audit.actor.type, actorId: audit.actor.id, action: audit.action, targetType: audit.target.type, targetId: audit.target.id, outcome: audit.outcome, correlationId: audit.correlationId, causationId: audit.causationId, metadata: audit.metadata, occurredAt: new Date(audit.occurredAt) } }); await transaction.outboxEvent.create({ data: { id: event.id, householdId: event.householdId, aggregateType: event.aggregate.type, aggregateId: event.aggregate.id, eventType: event.type, schemaVersion: event.schemaVersion, correlationId: event.correlationId, causationId: event.causationId, references: event.references, occurredAt: new Date(event.occurredAt) } });
}
export async function loadMealPlan(database: PrismaClient, input: { actor: Actor; date: DateOnly; now: Date }) { parseDateOnly(input.date); return database.$transaction(async (transaction) => { const member = await authorizeMeals(transaction as PrismaClient, input.actor, "meals.read", input.now); const entries = await transaction.mealPlanEntry.findMany({ where: { householdId: member.householdId, date: input.date, archivedAt: null }, orderBy: [{ mealSlot: "asc" }, { label: "asc" }, { id: "asc" }] }); const canManage = authorize({ context: input.actor.context, role: member.role, grants: input.actor.grants, request: { householdId: member.householdId, permission: "meals.manage", appId: "meals" }, now: input.now }).allowed; return { entries, canManage }; }, { isolationLevel: "Serializable" }); }
export async function createMealPlanEntry(database: PrismaClient, input: { actor: Actor; date: DateOnly; mealSlot: MealSlot; label: string; commandId: string; now: Date }) { const date = parseDateOnly(input.date).toString(); if (!slots.has(input.mealSlot)) throw new MealCommandError("mealSlot must be a supported value."); const label = boundedText(input.label, "label"); const commandId = boundedCommandId(input.commandId); return database.$transaction(async (transaction) => { const member = await authorizeMeals(transaction as PrismaClient, input.actor, "meals.manage", input.now); const existing = await transaction.mealPlanEntry.findUnique({ where: { creationCommandId: commandId } }); if (existing !== null) { if (existing.householdId !== member.householdId) throw new MealCommandError("commandId cannot cross household boundaries."); return existing; } const entry = await transaction.mealPlanEntry.create({ data: { householdId: member.householdId, date, mealSlot: input.mealSlot, label, creationCommandId: commandId } }); await evidence(transaction as PrismaClient, member.householdId, member.id, entry.id, input.now); return entry; }, { isolationLevel: "Serializable" }); }
