import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
const databaseUrl = process.env.LIFE_CHAT_INTEGRATION_DATABASE_URL;
describe.skipIf(databaseUrl === undefined)("meal repository integration", () => {
  it("persists only enabled household meal plans and records the command evidence", async () => {
    const { createPostgresAdapter } = await import("./postgres-adapter"); const { PrismaClient } = await import("../../generated/prisma/client"); const { setHouseholdMiniAppEnabled } = await import("./identity-repository"); const { createMealPlanEntry, loadMealPlan, MealCommandError } = await import("./meal-repository"); const database = new PrismaClient({ adapter: createPostgresAdapter(databaseUrl!) });
    try { const suffix = randomUUID(); const now = new Date("2026-08-20T12:00:00.000Z"); const household = await database.household.create({ data: { id: `meals-household-${suffix}`, name: "Meals" } }); const otherHousehold = await database.household.create({ data: { id: `meals-other-${suffix}`, name: "Other" } }); const adultSubject = await database.user.create({ data: { id: `meals-adult-subject-${suffix}`, name: "Adult", email: `meals-adult-${suffix}@example.test` } }); const childSubject = await database.user.create({ data: { id: `meals-child-subject-${suffix}`, name: "Child", email: `meals-child-${suffix}@example.test` } }); const otherSubject = await database.user.create({ data: { id: `meals-other-subject-${suffix}`, name: "Other", email: `meals-other-${suffix}@example.test` } }); const adult = await database.member.create({ data: { id: `meals-adult-${suffix}`, householdId: household.id, authenticatedSubjectId: adultSubject.id, displayName: "Adult", role: "adult", lifecycle: "active" } }); const child = await database.member.create({ data: { id: `meals-child-${suffix}`, householdId: household.id, authenticatedSubjectId: childSubject.id, displayName: "Child", role: "child", lifecycle: "active" } }); const other = await database.member.create({ data: { id: `meals-other-${suffix}`, householdId: otherHousehold.id, authenticatedSubjectId: otherSubject.id, displayName: "Other", role: "adult", lifecycle: "active" } }); const actor = (subjectId: string, memberId: string, householdId = household.id) => ({ context: { authenticatedSubjectId: subjectId, memberId, householdId }, grants: [] }); const adultActor = actor(adultSubject.id, adult.id); const childActor = actor(childSubject.id, child.id); const otherActor = actor(otherSubject.id, other.id, otherHousehold.id);
      await expect(createMealPlanEntry(database, { actor: adultActor, date: "2026-08-20", mealSlot: "dinner", label: "Pasta", commandId: `meal-${suffix}`, now })).rejects.toThrow(MealCommandError); await setHouseholdMiniAppEnabled(database, { actor: adultActor, appId: "meals", enabled: true, expectedVersion: 0, commandId: `enable-meals-${suffix}`, now }); await setHouseholdMiniAppEnabled(database, { actor: otherActor, appId: "meals", enabled: true, expectedVersion: 0, commandId: `enable-other-meals-${suffix}`, now }); const meal = await createMealPlanEntry(database, { actor: adultActor, date: "2026-08-20", mealSlot: "dinner", label: "Pasta", commandId: `meal-${suffix}`, now }); expect((await createMealPlanEntry(database, { actor: adultActor, date: "2026-08-21", mealSlot: "lunch", label: "Ignored", commandId: `meal-${suffix}`, now })).id).toBe(meal.id); await expect(createMealPlanEntry(database, { actor: childActor, date: "2026-08-20", mealSlot: "dinner", label: "Blocked", commandId: `child-meal-${suffix}`, now })).rejects.toThrow(MealCommandError); expect(await loadMealPlan(database, { actor: childActor, date: "2026-08-20", now })).toMatchObject({ entries: [{ id: meal.id, label: "Pasta" }], canManage: false }); await expect(loadMealPlan(database, { actor: otherActor, date: "2026-08-20", now })).resolves.toMatchObject({ entries: [] }); expect(await database.auditEvent.count({ where: { householdId: household.id, action: "meal.plan.create" } })).toBe(1); expect(await database.outboxEvent.count({ where: { householdId: household.id, eventType: "meal.plan.created.v1" } })).toBe(1);
    } finally { await database.$disconnect(); }
  });
});
