import type { PrismaClient } from "../../generated/prisma/client";
import { createAuditEvent, createDomainEvent, newCorrelationId } from "./audit-event";
import type { ActiveHouseholdContext } from "./identity-context";
import { loadHouseholdMiniAppConfiguration } from "./identity-repository";
import { activationEligibility } from "./mini-app-registry";
import { authorize, type CapabilityGrant } from "./permission-engine";

export class ProjectCommandError extends Error {}
type Actor = { context: ActiveHouseholdContext; grants: readonly CapabilityGrant[] };
function text(value: string) { const result = value.trim(); if (result.length === 0 || result.length > 200 || /[\r\n\u0000]/.test(result)) throw new ProjectCommandError("label must be 1–200 characters without control characters."); return result; }
function command(value: string) { if (value.trim().length === 0 || value.length > 200) throw new ProjectCommandError("commandId must be a bounded opaque identifier."); return value; }
async function member(database: PrismaClient, actor: Actor, now: Date) { const result = await database.member.findFirst({ where: { id: actor.context.memberId, householdId: actor.context.householdId, authenticatedSubjectId: actor.context.authenticatedSubjectId, lifecycle: "active", OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] } }); if (result === null || result.role === "guest" || !authorize({ context: actor.context, role: result.role, grants: actor.grants, request: { householdId: result.householdId, permission: "projects.manage", appId: "projects" }, now }).allowed) throw new ProjectCommandError("Projects is not available to this household member."); const configuration = await loadHouseholdMiniAppConfiguration(database, result.householdId); if (!activationEligibility("projects", configuration).eligible) throw new ProjectCommandError("Projects and Shared Lists must be enabled for this household."); return result; }
export async function createProject(database: PrismaClient, input: { actor: Actor; label: string; scope: "household" | "personal"; commandId: string; now: Date }) { const label = text(input.label); const commandId = command(input.commandId); return database.$transaction(async (transaction) => { const actor = await member(transaction as PrismaClient, input.actor, input.now); const existing = await transaction.project.findUnique({ where: { creationCommandId: commandId } }); if (existing !== null) { if (existing.householdId !== actor.householdId) throw new ProjectCommandError("commandId cannot cross household boundaries."); return existing; } const project = await transaction.project.create({ data: { householdId: actor.householdId, ownerMemberId: input.scope === "personal" ? actor.id : null, label, scope: input.scope, creationCommandId: commandId } }); const correlationId = newCorrelationId(); const audit = createAuditEvent({ householdId: actor.householdId, actor: { type: "member", id: actor.id }, action: "project.create", target: { type: "project", id: project.id }, outcome: "succeeded", correlationId, causationId: null, occurredAt: input.now.toISOString(), metadata: { scope: input.scope } }); const event = createDomainEvent({ householdId: actor.householdId, aggregate: { type: "project", id: project.id }, type: "project.created.v1", correlationId, causationId: audit.id, occurredAt: input.now.toISOString(), references: {} }); await transaction.auditEvent.create({ data: { id: audit.id, householdId: audit.householdId, actorType: audit.actor.type, actorId: audit.actor.id, action: audit.action, targetType: audit.target.type, targetId: audit.target.id, outcome: audit.outcome, correlationId: audit.correlationId, causationId: audit.causationId, metadata: audit.metadata, occurredAt: new Date(audit.occurredAt) } }); await transaction.outboxEvent.create({ data: { id: event.id, householdId: event.householdId, aggregateType: event.aggregate.type, aggregateId: event.aggregate.id, eventType: event.type, schemaVersion: event.schemaVersion, correlationId: event.correlationId, causationId: event.causationId, references: event.references, occurredAt: new Date(event.occurredAt) } }); return project; }, { isolationLevel: "Serializable" }); }
