import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
const databaseUrl = process.env.LIFE_CHAT_INTEGRATION_DATABASE_URL;
describe.skipIf(databaseUrl === undefined)("project repository integration", () => { it("creates scoped projects only for authorized adults", async () => {
  const { createPostgresAdapter } = await import("./postgres-adapter"); const { PrismaClient } = await import("../../generated/prisma/client"); const { setHouseholdMiniAppEnabled } = await import("./identity-repository"); const { createProject, ProjectCommandError } = await import("./project-repository"); const database = new PrismaClient({ adapter: createPostgresAdapter(databaseUrl!) });
  try { const suffix = randomUUID(); const now = new Date("2026-08-21T13:00:00.000Z"); const household = await database.household.create({ data: { id: `projects-household-${suffix}`, name: "Projects" } }); const adultSubject = await database.user.create({ data: { id: `projects-adult-subject-${suffix}`, name: "Adult", email: `projects-adult-${suffix}@example.test` } }); const childSubject = await database.user.create({ data: { id: `projects-child-subject-${suffix}`, name: "Child", email: `projects-child-${suffix}@example.test` } }); const adult = await database.member.create({ data: { id: `projects-adult-${suffix}`, householdId: household.id, authenticatedSubjectId: adultSubject.id, displayName: "Adult", role: "adult", lifecycle: "active" } }); const child = await database.member.create({ data: { id: `projects-child-${suffix}`, householdId: household.id, authenticatedSubjectId: childSubject.id, displayName: "Child", role: "child", lifecycle: "active" } }); const actor = (subject: string, member: string) => ({ context: { authenticatedSubjectId: subject, memberId: member, householdId: household.id }, grants: [] }); const adultActor = actor(adultSubject.id, adult.id); const childActor = actor(childSubject.id, child.id);
    await expect(createProject(database, { actor: adultActor, label: "Plan trip", scope: "household", commandId: `project-${suffix}`, now })).rejects.toThrow(ProjectCommandError); await setHouseholdMiniAppEnabled(database, { actor: adultActor, appId: "shared-lists", enabled: true, expectedVersion: 0, commandId: `enable-lists-${suffix}`, now }); await setHouseholdMiniAppEnabled(database, { actor: adultActor, appId: "projects", enabled: true, expectedVersion: 0, commandId: `enable-projects-${suffix}`, now }); const project = await createProject(database, { actor: adultActor, label: "Plan trip", scope: "personal", commandId: `project-${suffix}`, now }); expect(project).toMatchObject({ householdId: household.id, ownerMemberId: adult.id, scope: "personal" }); expect((await createProject(database, { actor: adultActor, label: "Ignored", scope: "household", commandId: `project-${suffix}`, now })).id).toBe(project.id); await expect(createProject(database, { actor: childActor, label: "Blocked", scope: "household", commandId: `child-${suffix}`, now })).rejects.toThrow(ProjectCommandError); expect(await database.auditEvent.count({ where: { householdId: household.id, action: "project.create" } })).toBe(1); expect(await database.outboxEvent.count({ where: { householdId: household.id, eventType: "project.created.v1" } })).toBe(1);
  } finally { await database.$disconnect(); }
}); });
