import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
const databaseUrl = process.env.LIFE_CHAT_INTEGRATION_DATABASE_URL;
describe.skipIf(databaseUrl === undefined)("reward repository integration", () => {
  it("keeps non-financial rewards and adult decisions household-scoped and replay-safe", async () => {
    const { createPostgresAdapter } = await import("./postgres-adapter"); const { PrismaClient } = await import("../../generated/prisma/client"); const { setHouseholdMiniAppEnabled } = await import("./identity-repository"); const { createReward, decideRewardRequest, loadRewardWorkspace, requestReward, RewardCommandError, RewardConflictError } = await import("./reward-repository");
    const database = new PrismaClient({ adapter: createPostgresAdapter(databaseUrl!) });
    try {
      const suffix = randomUUID(); const now = new Date("2026-08-20T12:00:00.000Z");
      const household = await database.household.create({ data: { id: `rewards-household-${suffix}`, name: "Rewards" } }); const otherHousehold = await database.household.create({ data: { id: `rewards-other-${suffix}`, name: "Other" } });
      const adultSubject = await database.user.create({ data: { id: `rewards-adult-subject-${suffix}`, name: "Adult", email: `rewards-adult-${suffix}@example.test` } }); const childSubject = await database.user.create({ data: { id: `rewards-child-subject-${suffix}`, name: "Child", email: `rewards-child-${suffix}@example.test` } }); const otherSubject = await database.user.create({ data: { id: `rewards-other-subject-${suffix}`, name: "Other", email: `rewards-other-${suffix}@example.test` } });
      const adult = await database.member.create({ data: { id: `rewards-adult-${suffix}`, householdId: household.id, authenticatedSubjectId: adultSubject.id, displayName: "Adult", role: "adult", lifecycle: "active" } }); const child = await database.member.create({ data: { id: `rewards-child-${suffix}`, householdId: household.id, authenticatedSubjectId: childSubject.id, displayName: "Child", role: "child", lifecycle: "active" } }); const other = await database.member.create({ data: { id: `rewards-other-${suffix}`, householdId: otherHousehold.id, authenticatedSubjectId: otherSubject.id, displayName: "Other", role: "adult", lifecycle: "active" } });
      const actor = (subjectId: string, memberId: string, householdId = household.id) => ({ context: { authenticatedSubjectId: subjectId, memberId, householdId }, grants: [] }); const adultActor = actor(adultSubject.id, adult.id); const childActor = actor(childSubject.id, child.id); const otherActor = actor(otherSubject.id, other.id, otherHousehold.id);
      await setHouseholdMiniAppEnabled(database, { actor: adultActor, appId: "chores", enabled: true, expectedVersion: 0, commandId: `enable-chores-${suffix}`, now }); await setHouseholdMiniAppEnabled(database, { actor: adultActor, appId: "rewards", enabled: true, expectedVersion: 0, commandId: `enable-rewards-${suffix}`, now }); await setHouseholdMiniAppEnabled(database, { actor: otherActor, appId: "chores", enabled: true, expectedVersion: 0, commandId: `enable-other-chores-${suffix}`, now }); await setHouseholdMiniAppEnabled(database, { actor: otherActor, appId: "rewards", enabled: true, expectedVersion: 0, commandId: `enable-other-rewards-${suffix}`, now });
      const reward = await createReward(database, { actor: adultActor, label: "Choose movie", commandId: `reward-${suffix}`, now }); expect((await createReward(database, { actor: adultActor, label: "Ignored", commandId: `reward-${suffix}`, now })).id).toBe(reward.id); await expect(createReward(database, { actor: childActor, label: "Blocked", commandId: `child-reward-${suffix}`, now })).rejects.toThrow(RewardCommandError);
      const request = await requestReward(database, { actor: childActor, rewardId: reward.id, commandId: `request-${suffix}`, now }); expect((await requestReward(database, { actor: childActor, rewardId: reward.id, commandId: `request-${suffix}`, now })).id).toBe(request.id); await expect(requestReward(database, { actor: otherActor, rewardId: reward.id, commandId: `cross-request-${suffix}`, now })).rejects.toThrow(RewardCommandError);
      expect(await loadRewardWorkspace(database, { actor: childActor, now })).toMatchObject({ rewards: [{ id: reward.id }], requests: [{ id: request.id, state: "requested" }], canManage: false, canApprove: false });
      const approved = await decideRewardRequest(database, { actor: adultActor, requestId: request.id, state: "approved", commandId: `approve-${suffix}`, now }); expect(approved).toMatchObject({ id: request.id, state: "approved", decidedByMemberId: adult.id }); expect((await decideRewardRequest(database, { actor: adultActor, requestId: request.id, state: "approved", commandId: `approve-${suffix}`, now })).id).toBe(request.id); await expect(decideRewardRequest(database, { actor: adultActor, requestId: request.id, state: "rejected", commandId: `reject-${suffix}`, now })).rejects.toThrow(RewardConflictError); await expect(decideRewardRequest(database, { actor: childActor, requestId: request.id, state: "approved", commandId: `child-approve-${suffix}`, now })).rejects.toThrow(RewardCommandError);
      expect(await database.auditEvent.count({ where: { householdId: household.id, action: { startsWith: "reward." } } })).toBe(3); expect(await database.outboxEvent.count({ where: { householdId: household.id, eventType: { startsWith: "reward." } } })).toBe(3);
    } finally { await database.$disconnect(); }
  });
});
